### PR TITLE
LU-3176: remove segfault-handler

### PR DESCRIPTION
**Pull request by stepancar**
electron fails on this package

Solutions I followed on github related to this question, didn't work for me, decided to just drop it
 
Screenshot 2024-01-09 at 1 07 09 AM

### CODE REVIEW

**Comment by antoineMoPa** [comment]
@stepancar the error in your logs just seem like you have built in one node version and used in another. maybe you can try again?

- Remove all node_modules folder
- Yarn install

**Comment by stepancar** [comment]
@antoineMoPa , you can see that it says that it has 115 version, but requires 106.
It's because, our environment is 115 - nodejs 20,
but electron uses node 18 under the hood.

I probably will find a solution to ask electron to rebuild it

**Comment by michaeljherrmann** [comment]
If it's just for testing electron, maybe we could just comment it out for now and revisit it later (if we don't use electron just add it back, if we do use it then do the fix?). Seems like this is mainly just for debug info, so it's probably fine?

**Comment by stepancar** [comment]
@michaeljherrmann @antoineMoPa , this thing used for debug.
Normal way to do that is to sync electron / enwjs version of node + node on localhost / on production.

It's tricky, because electron we use uses nodejs 18.

Another way to do this thing is to ask electron-forge to rebuild, but it didn;t work for me, the same time nwjs does not have rebuild

I don't see easier way to  to support all environments now.
I believe, nothing bad will happen if we remove it. commenting out works for me to. I can put it to cleanup ticket, after we done it on production

**Pull request merged**
